import viewed1 from '../../assets/viewedProduct/a1.webp'
import viewed2 from '../../assets/viewedProduct/a2.webp'
import viewed3 from '../../assets/viewedProduct/a3.webp'
import viewed4 from '../../assets/viewedProduct/a4.webp'

export const viewedProduct = [
    {
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: '3.190.000',
        priceSale: '2.190.000',
        salePercent: '31', 
        ratingCount: 5,
    },
]