import viewed1 from '../assets/viewedProduct/a1.webp'
import viewed2 from '../assets/viewedProduct/a2.webp'
import viewed3 from '../assets/viewedProduct/a3.webp'
import viewed4 from '../assets/viewedProduct/a4.webp'

export const productList = [
    {
        title: 'PC bán chạy',
        method: 'Trả góp 0%',
        products: [
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
                indexTech: [
                    'i3 10100F',
                    'RTX 4060',
                    'B760',
                    '16BG',
                    '1TB',
                ]
            },
        ],
        brands: [
            'PC I3',
            'PC I5',
            'PC I7',
            'PC I9',
            'PC R3',
            'PC R5',
            'PC R7',
            'PC R9',
        ]
    },
    {
        title: 'Laptop gaming bán chạy',
        method: 'Miễn phí giao hàng',
        products: [
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
        
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
        ],
        brands: [
            'ASUS',
            'ACER',
            'MSI',
            'LENOVO',
            'GIGABYTE',
            'DELL',
        ]
    },
    {
        title: 'Laptop văn phòng bán chạy',
        method: 'Miễn phí giao hàng',
        products: [
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
        
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
        ],
        brands: [
            'ASUS',
            'MSI',
            'LENOVO',
            'DELL',
            'LG',
            'ACER',
        ]
    },
    {
        title: 'Chuột bán chạy',
        method: 'Giao hàng toàn quốc',
        products: [
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
        
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
        ],
        brands: [
            'Logitech',
            'Razer',
            'Asus',
            'Corsair',
            'Dare-U',
            'Rapoo',
        ]
    },
    {
        title: 'Bàn phím bán chạy',
        method: 'Giao hàng toàn quốc',
        products: [
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
        
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
        ],
        brands: [
            'Akko',
            'Asus',
            'Razer',
            'Logitech',
            'Leopold',
            'Dare-U',
        ]
    },
    {
        title: 'Màn hình bán chạy',
        method: 'Bảo hành 1 đổi 1',
        products: [
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
        
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
                src: viewed2,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
                src: viewed3,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
                src: viewed4,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
            {
                href: '#',
                name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
                src: viewed1,
                price: '3.190.000',
                priceSale: '2.190.000',
                salePercent: '31', 
                ratingCount: 5,
            },
        ],
        brands: [
            'LG',
            'Asus',
            'ViewSonic',
            'Dell',
            'Gigabyte',
            'AOC',
            'Acer',
            'HKC',
        ]
    },
    
]

