import viewed1 from '../assets/viewedProduct/a1.webp'
import viewed2 from '../assets/viewedProduct/a2.webp'
import viewed3 from '../assets/viewedProduct/a3.webp'
import viewed4 from '../assets/viewedProduct/a4.webp'

export const computerList = [
    {
        id: 1,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 1,
            name: '',
            slug: '',

        },
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 2,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 1,
            name: '',
            slug: '',

        },
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 3,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 1,
            name: '',
            slug: '',

        },
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 4,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 1,
            name: '',
            slug: '',

        },
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 5,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 6,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 7,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 8,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 9,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
    {
        id: 10,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        indexTech: [
            'i3 10100F',
            'RTX 4060',
            'B760',
            '16BG',
            '1TB',
        ]
    },
]
        
export const laptopGamingList = [
        
    {
        id: 1,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,

    },
    {
        id: 2,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 3,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 4,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 5,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 6,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 7,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 8,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 9,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 10,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
]
export const laptopOfficeOList = [
    {
        id: 1,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,

    },
    {
        id: 2,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 3,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 4,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 5,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 6,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 7,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 8,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 9,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 10,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },

]
export const mouseList = [
    {
        id: 1,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,

    },
    {
        id: 2,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 3,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 4,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 5,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 6,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 7,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 8,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 9,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 10,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
]
export const keyboardList = [
    {
        id: 1,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,

    },
    {
        id: 2,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 3,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 4,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 5,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 6,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 7,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 8,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 9,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
    {
        id: 10,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
    },
]
export const screenList = [
    {
        id: 1,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 1,
            name: 'Chuột máy tính',
            slug: 'chuot-may-tinh',
        }

    },
    {
        id: 2,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 2,
            name: 'Màn hình máy tính',
            slug: 'man-hinh-may-tinh',
        }
    },
    {
        id: 3,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 3,
            name: 'Màn hình máy tính',
            slug: 'man-hinh-may-tinh',
        }
    },
    {
        id: 4,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 4,
            name: 'Màn hình máy tính',
            slug: 'man-hinh-may-tinh',
        }
    },
    {
        id: 5,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 5,
            name: 'Chuột máy tính',
            slug: 'chuot-may-tinh',
        }
    },
    {
        id: 6,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 6,
            name: 'Chuột máy tính',
            slug: 'chuot-may-tinh',
        }
    },
    {
        id: 7,
        href: '#',
        name: 'Màn hình ASUS ROG Strix XG27AQMR 27" IPS 2K 300Hz 1ms G-Sync',
        src: viewed2,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 7,
            name: 'Màn hình máy tính',
            slug: 'man-hinh-may-tinh',
        }
    },
    {
        id: 8,
        href: '#',
        name: 'Màn hình Acer KG270-X1 27" IPS 200Hz Gsync chuyên game',
        src: viewed3,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 8,
            name: 'Màn hình máy tính',
            slug: 'man-hinh-may-tinh',
        }
    },
    {
        id: 9,
        href: '#',
        name: 'Màn hình Viewsonic VA2432-H 24" IPS 100Hz viền mỏng',
        src: viewed4,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 9,
            name: 'Màn hình máy tính',
            slug: 'man-hinh-may-tinh',
        }
    },
    {
        id: 10,
        href: '#',
        name: 'Chuột Steelseries Aerox 3 Wireless Onyx',
        src: viewed1,
        price: 3190000,
        priceSale: 2190000,
        quantity: 1,
        salePercent: '31', 
        ratingCount: 5,
        category: {
            id: 10,
            name: 'Chuột máy tính',
            slug: 'chuot-may-tinh',
        }
    },
]


